### PR TITLE
Task more ship view

### PR DESCRIPTION
**Pull request by royfalk**
Finish moving content to python.

Code Changes:
- [x] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation _base computer only_

### CODE REVIEW

**Comment by evertvorster** [comment]
Hi there!

I see this one has a conflict with basecomputer.cpp. 
I'll test this branch, but that merge conflict should be resolved, please.

**Comment by royfalk** [comment]
> I see this one has a conflict with basecomputer.cpp.

I have no idea why it required conflict resolution. But I resolved it.

**Review by BenjamenMeyer — APPROVED** [review]

**Review by evertvorster — APPROVED** [review]
I play tested this, and ship view looks absolutely normal. 

A nice touch is the more verbose console output. Thanks. 

This PR is approved!

**Review by evertvorster — APPROVED** [review]
I had a good go at it, and the PR does not introduce any bugs that I can see. 

Approved.

**Pull request merged**
