### PR TITLE
Refactor: Static Game Config, Part B

### PR DESCRIPTION
**Pull request by stephengtuggy**
Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [In Progress] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [ ] This is a documentation change only

Issues:
- Please list any related issues

Purpose:
- What is this pull request trying to do? Convert over the majority of the game configuration settings to use the new `configuration()->…` approach. Also address a few other things in the process, such as refactoring the CMake stuff to use [CMake generator expressions](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html?highlight=generator%20expressions#id4), and refactoring the vs_logging stuff to use a Meyers singleton as well.
- What release is this for? 0.9.x, presumably
- Is there a project or milestone we should apply this to? 0.9.x, presumably

### CODE REVIEW

**Comment by evertvorster** [comment]
This PR does not cleanly patch against git master....

**Comment by stephengtuggy** [comment]
> This PR does not cleanly patch against git master....

Hmm. I know I was having some issues with my new CMake generator expressions causing the builds to fail. Is that what you were referring to? Or is there something else as well?

**Comment by evertvorster** [comment]
The build method I use is to get the latest git master, and then apply the PR as a patch. The patch is obtained by downloading https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/679.patch

As mentioned, this patch does not cleanly apply, and aborts my build script. 

This is the reported error:
patching file engine/src/system_factory.cpp
Reversed (or previously applied) patch detected!  Skipping patch.
3 out of 3 hunks ignored -- saving rejects to file engine/src/system_factory.cpp.rej

**Comment by evertvorster** [comment]
Hmm, instead of patch, I used git apply -3, and that allowed the patch to succeed without errors, and it's building happily now.

**Comment by stephengtuggy** [comment]
Closing this for now. I'll open another pull request once Part A of the static game config refactor is merged. Otherwise, merging all the different branches is going to get too complicated.

**Pull request closed without merging**
