### PR TITLE
Backport 463 0.8.x

### PR DESCRIPTION
**Pull request by BenjamenMeyer**
Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [ ] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [ ] This is a documentation change only

Issues:
- https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/463
- #149 

Purpose:
Backports #463 from master to 0.8.x

### CODE REVIEW

**Comment by BenjamenMeyer** [comment]
NOTE: I did do my basic test on this that I was doing before. We probably need to expand load testing a little.

I did the following tests:
- [ ] Test 1: Start Vega Strike, select "Load Game", select a game that shouldn't load (bad UTF-8 characters)
- [ ] Test 2: From the concourse, go to a terminal, load a game

In test 1, the bad game loaded per my previous experience.
In test 2, the bad game was detected and it refused to load it.

**Comment by P-D-E** [comment]
Test 1 depends on the Python call to the C++ check, and that one is in Assets; the test will fail with assets older than [pull 62](https://github.com/vegastrike/Assets-Production/pull/62).

**Review by Loki1950 — APPROVED** [review]

**Comment by ermo** [comment]
@BenjamenMeyer You might as well backport #470 here as well.

Remember to test with [Assets PR #62](https://github.com/vegastrike/Assets-Production/pull/62/files) merged.

**Comment by P-D-E** [comment]
Yes, #470 is needed too.

**Pull request merged**
