### PR TITLE
Enhancement: Updating the manpage

### PR DESCRIPTION
**Pull request by BenjamenMeyer**
Revisited the man page, cleaning up the formatting and updating
content.

Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [ ] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [x] This is a documentation change only

Issues:
- #96 - updating related information in the man page
- vegastrike/infrastructure-tracking/issues/6

Purpose:
Update the man page with more relevant and recent information. Clean up the formatting.

### CODE REVIEW

**Comment by BenjamenMeyer** [comment]
After merging here this should be ported to master.

**Review by Loki1950 — APPROVED** [review]
Looks good like all the contact options I would like to mention a thanks to Daniel Horn for starting the project mainly for legacy reasons

**Comment by BenjamenMeyer** [comment]
@Loki1950 thanks. Added Daniel Horn (@danielrh) in a special call out.

**Review by Loki1950 — APPROVED** [review]
Like your wording @BenjamenMeyer

**Pull request merged**
