### PR TITLE
Convert weapon_list.xml to weapons.json

### PR DESCRIPTION
**Pull request by royfalk**
Engine code to support the switch.
Note that this change and the previous one to units will break Wing Commander.

Code Changes:
- [x] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation

Issues:
- There are previous issues in the weapon_list that should be addressed at some point.
- The JSON library does not conform to the standard, making the code sloppier than I would have liked.
- Old files (units.csv and weapon_list.xml) have not been deleted yet.

### CODE REVIEW

**Review by BenjamenMeyer — APPROVED** [review]

**Comment by stephengtuggy** [comment]
Can we be sure to increment the Assets API version to 2 in this PR, as well?

**Comment by stephengtuggy** [comment]
Can we be sure to increment the Assets API version to 2 in this PR, as well?

**Comment by stephengtuggy** [comment]
Other than that, it looks all right.

**Comment by royfalk** [comment]
> Can we be sure to increment the Assets API version to 2 in this PR, as well?

How do I do that?

**Comment by BenjamenMeyer** [comment]
@royfalk increment the value at https://github.com/vegastrike/Vega-Strike-Engine-Source/blob/master/engine/CMakeLists.txt#L79

**Comment by royfalk** [comment]
As these are all part of the same "Epic", I'll increment once I'm done with it.
For anyone interested, I still need to modify the save game and the planets. Hopefully, that will get rid of legacy file formats.

**Comment by BenjamenMeyer** [comment]
We can increment at any time, but it should be done sooner than later so 9.8.x assets detect that master isn't necessarily compatible any more and we can see how things play work too

**Pull request merged**
