### PR TITLE
Introduce Mac OS X support!

### LINKED ISSUE #78: Figure out MacOS compilation
Continuation of #42.

### PR DESCRIPTION
**Pull request by stephengtuggy**
Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [Complete on Windows and Linux; macOS still pending] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [ ] This is a documentation change only

Issues:
- Please list any related issues
- Closes #78 

Purpose:
- What is this pull request trying to do? Add macOS support 🎉 
- What release is this for? 0.9.x/1.0.x, presumably
- Is there a project or milestone we should apply this to? 0.9.x/1.0.x

### CODE REVIEW

**Comment by daviewales** [comment]
This was what I installed with macports:

```
sudo port install cmake expat jpeg libpng libvorbis boost gtk3 gtkglext libsdl mesa libGLU freeglut
```

**Comment by stephengtuggy** [comment]
@daviewales Oh, crumbs. Looks like you have GTK installed, but in a different directory than expected. This is likely to be difficult to troubleshoot. A lot of the paths will be different.

Any chance you could install a later version of macOS, one that homebrew supports?

**Comment by daviewales** [comment]
Thanks for the hint! The following CMake patch fixed it. It compiles now. I just need to lookup how to get the data directory.

```
diff --git a/engine/FindGTK3.cmake b/engine/FindGTK3.cmake
index 6e0eaa0a7..36db3b4b5 100644
--- a/engine/FindGTK3.cmake
+++ b/engine/FindGTK3.cmake
@@ -179,6 +179,8 @@ FUNCTION(_GTK3_FIND_INCLUDE_DIR _var _hdr)
         /usr/openwin
         /sw
         /opt/local
+        /opt/local/include
+        /opt/local/lib
         $ENV{GTKMM_BASEPATH}
         [HKEY_CURRENT_USER\\SOFTWARE\\gtkmm\\2.4;Path]
         [HKEY_LOCAL_MACHINE\\SOFTWARE\\gtkmm\\2.4;Path]
```

**Comment by daviewales** [comment]
I've initialised the data submodule.

`./bin/vegasettings` works (in XQuartz, and non-retina, but it's progress!):

Screen Shot 2021-08-29 at 4 52 13 pm

I'm getting a segfault when I try to actually run VegaStrike. It makes my screen black for a second, then segfaults.

```
./bin/vegastrike-engine -d../data
[2021-08-29 16:54:53.742580] [0x00007fffb2044380] [trace]   Registering codec ogg
[2021-08-29 16:54:53.743256] [0x00007fffb2044380] [trace]   .

Legacy Mode: FALSE
 In path /Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/bin
Vega Strike
See http://www.gnu.org/copyleft/gpl.html for license details.

ARG #1 = -d../data
Using data dir specified on command line : ../data
GOT SUBDIR ARG =
Found data in ../data
Using /Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data as data directory
Using .vegastrike as the home directory
Found MODDIR = /Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data/mods
USING HOMEDIR : /Users/dwales/.vegastrike As the home directory
CONFIGFILE - Found a config file in home directory, using : /Users/dwales/.vegastrike/vegastrike.config
DATADIR - No datadir specified in config file
Force galaxy to /Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data/universe/milky_way.xml
SIMULATION_ATOM: 0.01
['/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python39.zip', '/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9', '/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload']
['', '/Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data/modules/builtin', '/Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data/modules/quests', '/Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data/modules/missions', '/Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data/modules/ai', '/Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data/modules', '/Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data/bases', '/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python39.zip', '/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9', '/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload']
zsh: segmentation fault  ./bin/vegastrike-engine -d../data
```

**Comment by daviewales** [comment]
Here's the output from ``--test-audio``:

```
❯ ./bin/vegastrike-engine -d../data --test-audio
[2021-08-29 18:43:56.957601] [0x00007fffb2044380] [trace]   Registering codec ogg
[2021-08-29 18:43:56.957983] [0x00007fffb2044380] [trace]   .

Legacy Mode: FALSE
 In path /Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/bin
Vega Strike
See http://www.gnu.org/copyleft/gpl.html for license details.

ARG #1 = -d../data
Using data dir specified on command line : ../data
ARG #2 = --test-audio
GOT SUBDIR ARG =
Found data in ../data
Using /Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data as data directory
Using .vegastrike as the home directory
Found MODDIR = /Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data/mods
USING HOMEDIR : /Users/dwales/.vegastrike As the home directory
CONFIGFILE - Found a config file in home directory, using : /Users/dwales/.vegastrike/vegastrike.config
DATADIR - No datadir specified in config file
Force galaxy to /Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/data/universe/milky_way.xml
SIMULATION_ATOM: 0.01
Creating scene manager...OK
Running rendererless tests...
  Clearing Scene
  Creating empty inactive scene
  Clearing Scene
    destroying "testScene"...done
  Creating empty active scene
  Clearing Scene
    destroying "testScene"...done
Running rendererful tests...
  Initializing renderer...
Uncaught exception: OpenAL error: unknown(Bad value) at /Users/dwales/Documents/Programming/not-my-code/Vega-Strike-Engine-Source/engine/src/audio/renderers/OpenAL/OpenALRenderer.cpp:168
FAILED
```

**Comment by stephengtuggy** [comment]
@daviewales Progress! That's good to see.

Can you try running Vega Strike from within a debugger?

**Review by nabaco — APPROVED** [review]

**Comment by nabaco** [comment]
I would consider merging this one and dealing with runtime issues in a separate issues. Thus we can at least add the Mac OS X build into CI and ensure no one breaks it again.
If someone can give me a build artifact, I can try to run it on my wife's laptop (she'd wouldn't like having a full dev environment in there 😄)

**Comment by stephengtuggy** [comment]
@nabaco Sounds like a plan. Thanks!

**Comment by nabaco** [comment]
@stephengtuggy we'd probably like to copy all the debug information that @daviewales has kindly supplied into a separate ticket.

**Comment by stephengtuggy** [comment]
@nabaco Yes.

@daviewales would you mind filing that separate ticket, with the information you have provided?

**Pull request merged**
