### PR TITLE
engine/src/cmd/movable.cpp: Apply ermo's suggested patch for arithmetic exception during PWCU game load

### LINKED ISSUE #474: PWCU + Vega Strike (Py3)
PWCU Assets cause the vegastrike-engine to crash on load.
```
$ ./vegastrike-engine -d~/Devel/opensource/vegastrike/assets/privateer_wcu
[2021-06-09 19:45:18.352662] [0x00007fa90af64800] [trace]   Registering codec ogg
[2021-06-09 19:45:18.352706] [0x00007fa90af64800] [trace]   .

Legacy Mode: FALSE
 In path ~/Devel/opensource/vegastrike/Vega-Strike-Engine-Source/py3/build-0.8.x
Vega Strike  
See http://www.gnu.org/copyleft/gpl.html for license details.

ARG #1 = -d~/Devel/opensource/vegastrike/assets/privateer_wcu
Using data dir specified on command line : ~/Devel/opensource/vegastrike/assets/privateer_wcu
GOT SUBDIR ARG = 
Found data in ~/Devel/opensource/vegastrike/assets/privateer_wcu
Using ~/Devel/opensource/vegastrike/assets/privateer_wcu as data directory
Using .pu as the home directory
Found MODDIR = ~/Devel/opensource/vegastrike/assets/privateer_wcu/mods
USING HOMEDIR : ~/.pu As the home directory 
CONFIGFILE - No config found in home : ~/.pu/vegastrike.config
CONFIGFILE - No home config file found, using datadir config file : ~/Devel/opensource/vegastrike/assets/privateer_wcu/vegastrike.config
DATADIR - No datadir specified in config file
Force galaxy to ~/Devel/opensource/vegastrike/assets/privateer_wcu/universe/wcuniverse.xml
SIMULATION_ATOM: 0.06
['/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload']
['', '~/Devel/opensource/vegastrike/assets/privateer_wcu/modules/builtin', '~/Devel/opensource/vegastrike/assets/privateer_wcu/modules/quests', '~/Devel/opensource/vegastrike/assets/privateer_wcu/modules/missions', '~/Devel/opensource/vegastrike/assets/privateer_wcu/modules/ai', '~/Devel/opensource/vegastrike/assets/privateer_wcu/modules', '~/Devel/opensource/vegastrike/assets/privateer_wcu/bases', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload']
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
Floating point exception (core dumped)
```

### PR DESCRIPTION
**Pull request by stephengtuggy**
Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [X] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [ ] This is a documentation change only

Issues:
- Please list any related issues
- Closes #474 

Purpose:
- What is this pull request trying to do? Port #509 to master
- What release is this for? 0.9.x
- Is there a project or milestone we should apply this to? 0.9.x

### CODE REVIEW

**Review by BenjamenMeyer — APPROVED** [review]

**Comment by stephengtuggy** [comment]
Finished play testing with VS:UtCS data set, on Windows. Note that I'm getting a segfault on exit, specifically when running Vega Strike from within the Visual Studio Code debugger. I will need to do some more investigation to make sure that this PR didn't introduce that problem.

**Comment by stephengtuggy** [comment]
Also tried testing with the PWCU data set on Windows, but it crashed on startup with an XML parse error. It sounds like PWCU wasn't working on Windows anyway, though, so not sure if this is a new issue either.

**Comment by ministerofinformation** [comment]
> Finished play testing with VS:UtCS data set, on Windows. Note that I'm getting a segfault on exit, specifically when running Vega Strike from within the Visual Studio Code debugger. I will need to do some more investigation to make sure that this PR didn't introduce that problem.

No - that's been there for a while. I forgot to file an issue for it, since it was only on-exit.

**Comment by stephengtuggy** [comment]
> > Finished play testing with VS:UtCS data set, on Windows. Note that I'm getting a segfault on exit, specifically when running Vega Strike from within the Visual Studio Code debugger. I will need to do some more investigation to make sure that this PR didn't introduce that problem.
> 
> No - that's been there for a while. I forgot to file an issue for it, since it was only on-exit.

@ministerofinformation OK. Yes, I just tried running the code on master, and I had the same issue. So it wasn't introduced by this PR.

**Comment by stephengtuggy** [comment]
And the code in this PR works fine with PWCU on Linux. So this is good to go. Merging.

**Pull request merged**
