### PR TITLE
Removed libboost from our source

### LINKED ISSUE #38: Drop vendoring of libboost
Per https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/33#issuecomment-609089044
VS provides a vendored copy of libboost. Is this still necessary? Or can we assume it is available?

### PR DESCRIPTION
**Pull request by nabaco**
Closes #38, related to #83.

I removed the boost source code from our repo, made the compilation with system boost default, and added a note in the README in case issues arise.

This PR is a proposition and not a decision.
In my opinion, if the build passes CI cleanly, we can merge it, but I'll leave it for the community to decide.

### CODE REVIEW

**Comment by nabaco** [comment]
Well darn, the build is failing for Ubuntu 14.04 GCC. Oddly enough, for Clang it passes :/

I'm think to enhance the CMake file to download libboost by itself, unpack it and compile it, if the system boost is not good enough.

Anyone knows what is the minimal Boost version we can use?

**Comment by Loki1950** [comment]
I will hold on that review till it complies with gcc

**Comment by BenjamenMeyer** [comment]
@nabaco since we have a limited amount of GitHub Package storage (500Mb), we might just want to setup a repository for developer assets where we can just drop a tarball (Unix/Linux) and Zip file (Windows) to support this. Then CMake could be setup to just download the repository into a specific folder (external-assets) and pull and extract whatever versions from there. That would also give us a bit better delta comparisons for any 3rd party library we need to track that way. $0.02 FWIW

**Comment by ermo** [comment]
Is Ubuntu 14.04 *seriously* a compile target?! There's been *3* LTS releases since then!

**Comment by nabaco** [comment]
> @nabaco since we have a limited amount of GitHub Package storage (500Mb), we might just want to setup a repository for developer assets where we can just drop a tarball (Unix/Linux) and Zip file (Windows) to support this. Then CMake could be setup to just download the repository into a specific folder (external-assets) and pull and extract whatever versions from there. That would also give us a bit better delta comparisons for any 3rd party library we need to track that way. $0.02 FWIW

What do we achieve by that? If we're going in the direction, might as well pull the sources from the origin, without duplicating them.

**Comment by BenjamenMeyer** [comment]
@nabaco we achieve having a copy that we can rely on in case something happens and the origin URL changes, goes off-line, etc. Gives us just a little more ability to reproduce throughout the years ahead. Otherwise, I fully agree just pull from the origin directly.

**Comment by royfalk** [comment]
I think we need to consider boost just like any other library. Do we keep a tarball for openAL? If not, why should we for boost? 
**I do agree that we should use the system boost** and expand it's usage. I have commits in progress that use boost filesystem for file operations instead of the old hacks currently used, for example.

**Comment by Loki1950** [comment]
The openAL tarball contains the windows .dll IIRC needed for building a windows installer creation

**Comment by royfalk** [comment]
It's going to be a bit hard to review, as github chokes on the number of files. 
Can we assume you only edited readme and cmakelist and deleted only stuff in the attached boost library?

**Comment by danielrh** [comment]
Do we have a designated person to track windows build/compat? When doing a lot of these refactors, making sure our Visual Studio builds go swimmingly could be an advantage-- with different memory allocators and better debugging mechanisms, Visual Studio has prevented Vega Strike from a number of pretty serious bugs

**Comment by nabaco** [comment]
> It's going to be a bit hard to review, as github chokes on the number of files.
> Can we assume you only edited readme and cmakelist and deleted only stuff in the attached boost library?

And `sh/vsbuild.sh`

**Comment by nabaco** [comment]
> Do we have a designated person to track windows build/compat? When doing a lot of these refactors, making sure our Visual Studio builds go swimmingly could be an advantage-- with different memory allocators and better debugging mechanisms, Visual Studio has prevented Vega Strike from a number of pretty serious bugs

This is still in progress, see #53 for more info. If you have some light to shed on the matter, we'll be glad to hear.

**Comment by BenjamenMeyer** [comment]
@danielrh no, we don't have the Windows build working yet. Once we do, we'll try to figure out how to add it to the PR gate check

**Comment by nabaco** [comment]
Conflict resolved, and since Ubuntu 14.04 LTS was removed, compilation passes.

**Comment by BenjamenMeyer** [comment]
@nabaco given there are 14,000+ files changed; which ones do I need to pay attention to for a final review? README and CMakeLists.txt?

**Comment by nabaco** [comment]
Yes, that's the two files that I have changed.

**Comment by BenjamenMeyer** [comment]
@nabaco thanks - assuming builds work; it's approved

**Pull request merged**
