### PR TITLE
Use boost for JSON parsing

### LINKED ISSUE #688: Migrate to the Boost JSON parser eventually?
@royfalk okay - WFM; but let's file an issue to migrate to the Boost one once we support the appropriate Boost version.

_Originally posted by @BenjamenMeyer in https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/686#discussion_r881887840_

### PR DESCRIPTION
**Pull request by royfalk**
This PR replaces singleson (json.*) with the standard boost JSON facilities.
Note: this still parses a text only JSON. We should move away to a proper JSON with types.

Please answer the following:

Code Changes:
- [x] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation _minimal. Check that game works._

Issues:
- Ship view appears broken. The entire area needs to be refactored, as there is duplicate code.

Fix #688

### CODE REVIEW

**Comment by royfalk** [comment]
> Ship view does not appear THAT broken to me.

Take a look at the console. Because the various stats are saved as x/y/z, the python script is unhappy.

> I think we should fix any obvious problems with the game before merging, though. It is the best time, after all.

I agree. However, this is not the right repo. You can test everything else

**Comment by evertvorster** [comment]
Merged in that fix for the turning response, and now of course it is fixed. I had a root around the ship view, and it appears OK. Also flew around a bit. Will do a little more testing, but so far this one looks good to go.

**Review by evertvorster — APPROVED** [review]
Ship view looks normal to me. 
I had a few battles, and the ships there also looked pretty normal. 
New Campaign had no new issues. 
Able to trade goods, and it all looks normal.

**Comment by evertvorster** [comment]
I do see some syntax warnings in the console, but it does not seem to affect the game.

**Comment by royfalk** [comment]
> I do see some syntax warnings in the console, but it does not seem to affect the game.

Please post them here and I'll check if they're relevant. It looks like there's more work to support Windows and CodeQL has some issues, so there will be at least one more commit.

**Comment by evertvorster** [comment]
These are the errors that I am seeing in the console:
```
Asset API Version: 3
/usr/share/vegastrike/modules/quests/quest_tutorial.py:840: SyntaxWarning: invalid escape sequence '\T'
  text = "CEPHID SECURITY INITIATIVE GIVES TRAINING FOR FLIGHT SAFETY\\\The Cephid Security Initiative (CSI) is offering training for pilots with the purpose of enhancing flight safety in and out of the system. "
/usr/share/vegastrike/modules/news.py:80: SyntaxWarning: invalid escape sequence '\T'
  newsfooter = "\\\\\This story was first broadcast on: "
/usr/share/vegastrike/modules/news.py:125: SyntaxWarning: invalid escape sequence '\T'
  STARDATE_TEXT = "\\\\\This story was first broadcast on: "
/usr/share/vegastrike/modules/dynamic_news.py:68: SyntaxWarning: invalid escape sequence '\T'
  STARDATE_TEXT = "\\\\\\\This story was first broadcast on: "
/usr/share/vegastrike/modules/quests/quest_dispute.py:156: SyntaxWarning: invalid escape sequence '\T'
  text = "PRIVATEER SAVES SHIPLOAD OF WOUNDED\\\Today, an unprecedented dispute about landing priorities took place close to a station in the Regallis system of Sol sector. "
/usr/share/vegastrike/modules/quests/quest_dispute.py:189: SyntaxWarning: invalid escape sequence '\T'
  text = "MALICIOUS MERCHANT MASSACRES MARXIST MERCY MISSION\\\Today, an unprecedented dispute about landing priorities took place close to a station in the Regallis system of Sol sector. "
/usr/share/vegastrike/modules/quests/quest_blockade.py:99: SyntaxWarning: invalid escape sequence '\I'
  text = "JUMP POINT BLOCKADE IN " + self.system + " SYSTEM\\\Intelligence has uncovered Aeran plans to invade Confederation space."
/usr/share/vegastrike/modules/quests/quest_shipyardbomb.py:63: SyntaxWarning: invalid escape sequence '\D'
  text = "NAVAL SHIPYARDS HIT BY BOMB\\\Disaster struck the Confederate Naval Shipyards orbiting Alpha Centauri hours ago, when a powerful explosive device detonated, crippling a fleet carrier that was nearing completion. "
```

**Comment by royfalk** [comment]
> These are the errors that I am seeing in the console:

I just took a look and these are indeed errors in the python scripts. For some reason, VS is now printing them, but they were always there.

Consider the first error in the string: "CEPHID SECURITY INITIATIVE GIVES TRAINING FOR FLIGHT SAFETY\\\The ..."
There are three backslashes followed by capital T.

I extracted this to a simple python program:
```
some_string = '\T'
print(some_string)
```
and got the same warning.

For now, I don't plan to fix this, as there may be something I'm missing. The game is publishing this string to C++. I'll need to do some more digging.

**Comment by royfalk** [comment]
It looks like the first warning gets triggered by finishing the tutorial. Can you confirm this?

**Comment by evertvorster** [comment]
Hi there!

Firstly, what I am testing:
I'm merging in task_bug_924, task_more_ship_view and task_boost_json

Using the current master of Assets, with task_more_config applied

I see these errors pop up when starting the game. Not loading any game or starting a new campaign, just loading the game and exiting. 

Of course, the more you play, the more these errors appears.

**Review by BenjamenMeyer — APPROVED** [review]

**Review by BenjamenMeyer — APPROVED** [review]

**Comment by BenjamenMeyer** [comment]
Looks like Windows is failing the builds on the Boost version as it has a newer version than expected.

**Comment by royfalk** [comment]
@BenjamenMeyer 

First, please turn your attention to my comment about Rocky Linux: "For some reason, all Linux distros use the apt-get of Ubuntu Noble. I don't even know what we're testing here."

Second, I've used the build-system-docker-images to try and reproduce the fail for ubuntu and failed. I downloaded noble, followed the github action. Even added the flags as required.

```
    1  git status
    2  dpkg -l | grep vim 
    3  cd ..
    4  cd Vega-Strike-Engine-Source/
    5  script/bootstrap 
    6  vim script/bootstrap
    7  apt install vim
    8  vim script/bootstrap
    9  script/bootstrap 
   10  echo $FLAGS
   11  export FLAGS="-DOpenGL_GL_PREFERENCE=LEGACY -DENABLE_PIE=OFF"
   12  script/cibuild
```

I am at a loss here.

**Comment by BenjamenMeyer** [comment]
Yeah, I've had trouble reproducing it too. Not sure why.

**Comment by royfalk** [comment]
Rocky Linux 9.4 can't compile on clang due to https://github.com/boostorg/mpl/issues/69.

**Comment by royfalk** [comment]
@BenjamenMeyer please review and confirm following changes:

- codeql.yml - move from ubuntu-latest (22) to 24.04
- gh-actions-pr.yml
   - remove old OS (boost < 1.75)
   - disable rocky linux 9.4 due to bug
   - re-run bootstrap
- bootstrap
   - debian bookworm - remove default installed boost1.74 and install 1.81.
   - Remove unsupported debian bullseye, ubuntu jammy and focal, Suse 15.2, 15.3, Rocky 8.0 to 8.10
- docker-entrypoint.sh
   - rerun bootstrap inside docker
- CMakeLists.txt
   - Suppress CMP0102 warning
   - Simplify boost process - remove option for internal boost and for old versions. If someone wants to, they can hack the game to do so. Why provide support for boost and not for other libraries?
   -

**Comment by royfalk** [comment]
@BenjamenMeyer 
I'm delaying this, so as not to step on #891.  
Please confirm that you're fine removing all those old OS's.

**Comment by BenjamenMeyer** [comment]
> @BenjamenMeyer 
> I'm delaying this, so as not to step on #891.  
> Please confirm that you're fine removing all those old OS's.

Yes, I'm fine with it for 0.10.x/master.
Thinking about getting my Cmake PR merged though even though Mac and Windows were giving me issues for some reason. We can think about ordering...I can probably handle the merge....need to update it anyway.

**Pull request merged**
