### PR TITLE
Integrate Travis-CI

### LINKED ISSUE #31: Add CI to VegaStrike
I think it might really boost development if we add CI/CD to this repository.
I have some experience with TravisCI, which is free for OpenSource projects.

I would suggest the following stages for CI integration:
- Check compilation on Ubuntu 18.04 LTS
- Check compilation on other platforms (MacOS, Windows, other Linux/UNIX distros)
- Implement code tests (I don't know if any exist already)

In the future, we can integrate CD which automates the creation of packages for different distro's upon releases, creation of documentation, etc.

### PR DESCRIPTION
**Pull request by nabaco**
Created initial .travis.yml based on https://github.com/BenjamenMeyer/samplingEngine/blob/master/.travis.yml, offered by @BenjamenMeyer.
Resolves #31

### CODE REVIEW

**Comment by nabaco** [comment]
Now only to make it pass the CI 🤣

**Comment by nabaco** [comment]
Switching to Bionic seems to have complicated things. It has only gcc-7.4
I think we should revise which compiler versions to use, and maybe test older compilers on older distros.

**Comment by BenjamenMeyer** [comment]
@nabaco sounds like a plan. I'm not sure what our official set of distro/compiler sets should be. @LifWirser might be able to provide some insight given he has managed to build it recently.

**Comment by nabaco** [comment]
Clang seems to have caught actual issues in the code.
```
In file included from /home/travis/build/vegastrike/Vega-Strike-Engine-Source/engine/setup/src/include/central.cpp:39:37: error: 

      ordered comparison between pointer and zero ('struct group *' and 'int')

/home/travis/build/vegastrike/Vega-Strike-Engine-Source/engine/src/cmd/ai/hard_coded_scripts.cpp        } while ((CURRENT = CURRENT->next) > 0);

                 ~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
```

We might need to either do some code cleanup to enable the CI, or mark the problematic compilers as expected failures, and do the code fixing under a different ticket.
I'll continue with this tomorrow.

**Comment by nabaco** [comment]
> @nabaco sounds like a plan. I'm not sure what our official set of distro/compiler sets should be. @LifWirser might be able to provide some insight given he has managed to build it recently.

I have managed to build recently too. The following works for sure:
- Ubuntu 18.04 + gcc/g++ 7.4 (WSL)
- Arch + gcc/g++ (need to check the version, but I guess latest :smile:)

**Comment by nabaco** [comment]
GCC fails too, with the following error:
```
[100%] Linking CXX executable vegastrike

/usr/bin/ld: cannot find -lboost_python

collect2: error: ld returned 1 exit status

CMakeFiles/vegastrike.dir/build.make:3060: recipe for target 'vegastrike' failed
```

The entire libboost topic is a mystery for me. Why are we including it in our code?
I know that we can install it from the package manager (libboost1.65-dev on Ubuntu 18.04), not to mention the warnings it throws with CMake.
Maybe @LifWirser can shine some more light on it?

**Comment by BenjamenMeyer** [comment]
@nabaco for this initial pass, let's focus on what we _know_ works; we can add other compilers via additional PRs. So feel free to add clang as a known failure for now, file an issue, and it can get fixed later. Thanks for seeing this through.

BTW - I think I'm getting the same boost-python error in my env; I haven't successfully built it yet and haven't had time to dig into it either Hopefully @LifWirser can take a look soon and give some feedback.

**Comment by nabaco** [comment]
## Success!!

It took some tinkering, but it works now as expected.
Now, if I get a final approval on this, I'll squash the branch, and you can merge it.

For future reference:
- To test .travis.yml go [here](https://config.travis-ci.com/explore)
- To skip a build due to a minor change (e.g. update README), include [skip travis] in the commit message. See [Travis-CI docs](https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build) for more details

Proposed next steps:
- Fix clang compilation
- Remove compilation warnings for both compilers (this can actually fix a bunch of bugs). See #29 
- Integrate a check for compilation warnings, so new ones won't be introduced in the future. (Maybe something like: `grep -i "warning" CMakeFiles\CMakeOutput.log`)

**Comment by BenjamenMeyer** [comment]
@nabaco go ahead an squash this, then I'll merge it.

**Comment by nabaco** [comment]
@BenjamenMeyer done

**Comment by nabaco** [comment]
Thank you @BenjamenMeyer!
Can anyone comment on the proposed next steps as I have written in my above comment? 33#issuecomment-607772765

Should I open an issue for each one or something?

**Comment by BenjamenMeyer** [comment]
@nabaco looks like possibly some core maintainer training; please be patient as we get the ball rolling, and keep the PRs coming.

I've got some priviledges, but I asked for them to help with the Project boards primarily so trying not to overstep my bounds. I'll try to help primarily from a project management point right now as we get communications and other things worked out. Just beware the ball might be slow for a bit, and hopefully we can get it going faster.

**Comment by royfalk** [comment]
_The entire libboost topic is a mystery for me. Why are we including it in our code?_
This is probably legacy. I vote we kick it out of the project and align with the rest of the programming world.

_I think we should revise which compiler versions to use, and maybe test older compilers on older distros._
I'm a cutting edge kind of guy, and it got me into trouble before. I vote we ditch older environments for building but not for playing. We require new if not newest compilers so we can clean the code as much as possible but release new version binaries for older systems as well. We're an open source project, it should be fun to contribute. No one likes to maintain legacy code. If we wanted to do that, we'd spend another hour at our day job. As an aside, the code is filled with ifdefs for MS Visual C 6 (circa mid-90's!) and Solaris. I think we can drop support for these.

_Can anyone comment on the proposed next steps as I have written in my above comment?
Should I open an issue for each one or something?_
Please do that. Also, please ask @Loki1950 to add you as a contributor. I don't know your background but you seem to know your stuff. I'm going to open two issues: 1. Project History 2. Current team status. From my talk with Loki, the older generation of programmers has moved on. Loki's been around for ages but he's not a C++ dev. It might be a good idea to start talking about where we want to take this project and how we want to do it. My vote is for Loki to be the project leader/mediator.

**Comment by BenjamenMeyer** [comment]
> _The entire libboost topic is a mystery for me. Why are we including it in our code?_
> This is probably legacy. I vote we kick it out of the project and align with the rest of the programming world.
> 

Filed #38 to track

> _I think we should revise which compiler versions to use, and maybe test older compilers on older distros._
> I'm a cutting edge kind of guy, and it got me into trouble before. I vote we ditch older environments for building but not for playing. We require new if not newest compilers so we can clean the code as much as possible but release new version binaries for older systems as well. We're an open source project, it should be fun to contribute. No one likes to maintain legacy code. If we wanted to do that, we'd spend another hour at our day job. As an aside, the code is filled with ifdefs for MS Visual C 6 (circa mid-90's!) and Solaris. I think we can drop support for these.

Filed #40 to track
> 
> _Can anyone comment on the proposed next steps as I have written in my above comment? Should I open an issue for each one or something?_
> Please do that. Also, please ask @Loki1950 to add you as a contributor. I don't know your background but you seem to know your stuff. I'm going to open two issues: 1. Project History 2. Current team status. From my talk with Loki, the older generation of programmers has moved on. Loki's been around for ages but he's not a C++ dev. It might be a good idea to start talking about where we want to take this project and how we want to do it. My vote is for Loki to be the project leader/mediator.

Filed #41 to track

**Comment by pyramid3d** [comment]
We may also want to support the newest compilers

> g++ --version
> g++ (Arch Linux 9.3.0-1) 9.3.0

libboost was included into the repo to allow for quick checkout and compile while maintaining compatibility with existing code (newer versions may break code). 

You can use system lib instead if you like (and make this one default for your local development) in engine/CMakeLists.txt:

> OPTION(USE_SYSTEM_BOOST "Use system boost" OFF)

**Pull request merged**
