### PR TITLE
Lib Component - Improvements to Resource

### PR DESCRIPTION
**Pull request by royfalk**
This is part of the lib component PRs.
Various bug fixes and additions to Resource class.
Add unit tests

Please answer the following:

Code Changes:
- [X] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation. Also wrote unit tests.
- [ ] This is a documentation change only

Issues:
- Loaded game had the ship constantly flying to the right.

### CODE REVIEW

**Review by BenjamenMeyer — APPROVED** [review]

**Comment by stephengtuggy** [comment]
Um, the issue with the ship constantly flying to the right sounds like a big deal to me. Can we get that fixed before we merge this?

I'm very glad you are adding more unit tests. We could certainly use more of those.

**Comment by royfalk** [comment]
> Um, the issue with the ship constantly flying to the right sounds like a big deal to me. Can we get that fixed before we merge this?
I've seen this bug before. That's definitely not something related to the Resource class. The save game in general is buggy as hell. When you load a game from another game, you don't find yourself in dock but in space. This will need a real deep dive into the system. 

From the looks of it, it's now failing with:
Could NOT find Python3 (missing: Python3_INCLUDE_DIRS Python3_LIBRARIES.
in Rocky Linux 8.7.
Can I merge?

**Comment by stephengtuggy** [comment]
> > Um, the issue with the ship constantly flying to the right sounds like a big deal to me. Can we get that fixed before we merge this?
> > I've seen this bug before. That's definitely not something related to the Resource class. The save game in general is buggy as hell. When you load a game from another game, you don't find yourself in dock but in space. This will need a real deep dive into the system.
> 
> From the looks of it, it's now failing with: Could NOT find Python3 (missing: Python3_INCLUDE_DIRS Python3_LIBRARIES. in Rocky Linux 8.7. Can I merge?

The Rocky Linux 8.7 failure is not a blocker. Our code in general doesn't build on Rocky Linux 8.x anymore  We're not going to support it any longer.

I would like to play test this a little bit before we merge, if you don't mind.

**Comment by royfalk** [comment]
> I would like to play test this a little bit before we merge, if you don't mind.
Be my guest.

**Review by stephengtuggy — APPROVED** [review]
Looks good to me. Play testing went fairly well also. I did not encounter the issue with the ship constantly flying to the right. Maybe it doesn't occur on Windows? Or with a joystick?

At any rate, I am satisfied that we can go ahead and merge this PR.

**Comment by stephengtuggy** [comment]
The one issue I did encounter was with the autopilot overshooting my destination, a medical station -- over and over and over. I don't think that's a new issue, but it might be. We'll probably want to troubleshoot that later.

**Pull request merged**
