### PR TITLE
CPack: Introduce BOOST_VER variable; fix libboost-* deps manually

### LINKED ISSUE #391: Vega Strike v0.7.0-beta1 Ubuntu bionic py3 installer missing at least one boost dependency
It doesn't specify the Boost date-time library as a .deb dependency, even though the Vega Strike binary needs it to run.

### PR DESCRIPTION
**Pull request by stephengtuggy**
Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [ ] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [ ] This is a documentation change only
- [X] This is a build system/packaging change only

Issues:
- Please list any related issues
Closes #391 

Purpose:
- What is this pull request trying to do? Fix the Boost dependency lists for the Debian and Ubuntu installers
- What release is this for? 0.7.x
- Is there a project or milestone we should apply this to? 0.7.x

### CODE REVIEW

**Review by Loki1950 — APPROVED** [review]
Why do distro hackers all add complexity to their babies besides their egos.

**Review by BenjamenMeyer — APPROVED** [review]
I assume this is from review of the dynamic data.

**Comment by stephengtuggy** [comment]
> I assume this is from review of the dynamic data.

Yes, it is.

**Comment by stephengtuggy** [comment]
@Loki1950 IIRC, this is something that @BenjamenMeyer and I had talked about: Adding a variable for the Boost version, so that we can easily switch Boost versions by changing it in one place, rather than half a dozen places. Now that you mention it, though, it does make the code look more complicated.

**Comment by BenjamenMeyer** [comment]
Since we don't have a uniform version across platforms the complication is necessary. Please port this to master, we can clean it up a little there if possible, but don't worry about doing so for 0.7.x.

Thanks!

**Pull request merged**
