### PR TITLE
Refactor cmake

### PR DESCRIPTION
**Pull request by BenjamenMeyer**
Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [ ] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [ ] This is a documentation change only
- [x] Build System Change

Issues:
- #56 

Purpose:
- refactor the CMake configuration to use the root of the repo as its base instead of the `engine` directory as its base; this will allow us to start factoring out the libraries easier without having to resort to any weird CMake-foo.

### CODE REVIEW

**Comment by BenjamenMeyer** [comment]
@stephengtuggy I can merge this after #789 is merged; generally plan on it though it shouldn't have much of an effect.

**Comment by stephengtuggy** [comment]
Nice work. That's a lot of build failures though. It seems that more work is still needed on this one.

**Comment by BenjamenMeyer** [comment]
> Nice work. That's a lot of build failures though. It seems that more work is still needed on this one.

yes, waiting until other PRs are done before fully going for this one.

**Comment by royfalk** [comment]
Can you start working again on this one? If so, what do you need?

I want to set aside some time for house cleaning (issues, old PRs, etc.) and not just development.

**Comment by BenjamenMeyer** [comment]
Yes I'm going to pick this up again for 0.10.x - I might start from scratch though. Just needed to locate my work.

**Comment by BenjamenMeyer** [comment]
closing this to restart on a new branch

**Pull request closed without merging**
