### PR TITLE
Add a LICENSE file

### LINKED ISSUE #26: Specify the License
Good open source repositories contain a file in the root called LICENSE that specifies what license they fall under. This enables everyone to know if the source is compatible with other libraries, projects, etc. Git Hub has an easy mechanism to set a known license from its list. I assume there is already one for VegaStrike and we just need to find it and put it in the right location.

This will also help enable people to contribute.

### PR DESCRIPTION
**Pull request by nabaco**
Moved the LICENSE file from doc/ to root
Resolves #26

### CODE REVIEW

**Comment by nabaco** [comment]
> I don't see a removal of the file from under `docs`; did you do a move or a copy?
> We need to only have the license in one place.

Removed.

**Comment by BenjamenMeyer** [comment]
@LifWirser At least a quick grep through the code doesn't show anything that references that file, though there is a file `vega-license` that the NSI stuff generates that is somehow related... so it's possible that something references it but:
```
$ grep LICENSE * -Rn
```
didn't find anything.

**Comment by nabaco** [comment]
@BenjamenMeyer @LifWirser is there anything I can do to progress this and my other PR?

**Comment by BenjamenMeyer** [comment]
@nabaco I'd like to get more familiar with building VS myself before I merge this.

@pyramid3d @stephengtuggy @Loki1950 @klaussfreire are the primary merge folks right now.

**Comment by Loki1950** [comment]
just did the merge BTW I can't log in to our forums getting a ssl err with chrome need to contact www2 who takes care of our hosting.

**Comment by BenjamenMeyer** [comment]
@Loki1950  I don't see the commit recorded in GitHub.

**Comment by nabaco** [comment]
Hi @Loki1950, looking at the latest master, the License file is still not in the root directory - FYI.

**Comment by Loki1950** [comment]
Just reopened the pull request not all that familiar with git's terms for various actions so could one of you walk me through it

**Comment by nabaco** [comment]
Usually the workflow with opensource in Github is as follows:
1. A contributor that doesn't have "write" permission to the project repository forks the project (makes a copy of the project under his account in Github).
2. He does all of his subsequent changes in the local copy. Usually, that is done on a side branch. The changes are committed (like making a revision in SVN) and pushed onto Github.
3. To add the changes to the original project, he opens a pull request (PR) from his copy to the original project. In the PR you can see the proposed changes, discuss them, see test results, etc.
4. Ones the PR is approved, someone with "write" permission can merge it into the master branch of the original project. This can be done in two ways:
    - Through the WebUI, with the green button that appears at the bottom.
    - Manually through the command-line. In that case, don't forget to push the new master onto Github after the merge

I hope that wasn't too much for your question 😄 In case you need more info: https://guides.github.com/introduction/flow/

If you still have more questions, I'll be glad to talk with you next week.

**Pull request merged**
