### PR TITLE
Enhancement: Re-enable dynamic dependency detection

### PR DESCRIPTION
**Pull request by BenjamenMeyer**
Dynamic dependency detection was fixed and the DEB files built
using `script/package` will properly use it. This re-enables the
CMake/CPack function to rely on it if it exists.

Dynamic dependency detection is preferred as it will make the
dependencies match up with what is actually needed based on an
examination of the binaries even if developers fail to specify it.
This is a more reliable method than static dependencies.

Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [ ] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [ ] This is a documentation change only
- [x] Build system change only - verified the Deb files that were built

Issues:
- #391 

Purpose:
Re-enables the preference to use the dynamic dependencies. Should preserve the static dependencies as a fall-back mechanism.

### CODE REVIEW

**Review by Loki1950 — APPROVED** [review]

**Review by stephengtuggy — COMMENTED** [review]
@BenjamenMeyer I have concerns that the auto-generated dependency list will be too specific. The fact that several Wayland libraries showed up in the list from your local system posted on #391  , seems to validate my concerns.

Thoughts?

**Comment by stephengtuggy** [comment]
Thanks for the hard work on this, by the way. The auto-generated dependency list is very informative, even if we don't end up using it verbatim.

**Comment by BenjamenMeyer** [comment]
If we know a better way to mix and match that'd be great. It just does an ldd analysis right now and grabs matching packages. Might need a tweak around grabbing the matching one that's installed versus and package; guessing that's why the wayland dependency might have shown up

**Comment by BenjamenMeyer** [comment]
to answer @stephengtuggy 's question about the dependencies we're going to merge this, cut a pre-alpha release, check it, and if we don't like the result we may revert this change, or at least not port it yet to 0.7.x.

**Pull request merged**
