### PR TITLE
Re-enable boost logging

### LINKED ISSUE #107: The boost::log stuff I put in got turned off
Need to turn it back on again, after figuring out how to get it to compile properly with the latest Boost. This is essential for proper VS debugging output.

Relates to #95

### PR DESCRIPTION
**Pull request by stephengtuggy**
So the issue with the code not compiling on the latest versions of Boost, was a real issue. I followed the guidance found [here](https://stackoverflow.com/a/55689686) to get past this.

Re-enabled the various places in the code that use `BOOST_LOG_TRIVIAL`. About 30 files in all. Re-enabled the `initLogging` function. Made a few other associated changes.

Testing steps completed:
Bought and sold cargo
Bought and sold ship upgrades
Flew between Atlantis and Serenity, docking at each multiple times
Picked a fight (and lost)
Jumped to Oldziey; landed on a rocky planet

I feel like I'm missing someone in terms of reviewers. Feel free to add anyone else who should be a reviewer on this PR.

Closes #107

### CODE REVIEW

**Comment by Loki1950** [comment]
Will let the others review the code @stephengtuggy first but I do think it's a good idea it should let us the fix the various errors in the vs logs with more info

**Comment by stephengtuggy** [comment]
Well, crap. Travis errored out. I will troubleshoot.

**Comment by stephengtuggy** [comment]
Looks like Travis is fixed.

**Comment by ermo** [comment]
@stephengtuggy 

I added a vs_dprintf in PR #87 -- if you want to change that to boost logging format, you're more than welcome to do so (I tried to do it myself, but it didn't compile back then so I figured I'd better leave it to the pros).

**Comment by BenjamenMeyer** [comment]
Please merge master

**Comment by stephengtuggy** [comment]
> BTW there is a way to increase the verbosity of the logs --verbose # where the num character is 1-5 not sure on this

I believe it is --debug=# where the num character is 1-3.

**Comment by stephengtuggy** [comment]
> Hi @stephengtuggy, shouldn't we just delete all `VSFileSystem::vs_dprintf` calls?

I would agree that that would be a good next step.

> 
> Additionally, can you show the results? Where will we find the log files? How will the look?

This is what the results look like on the console. Not sure yet how to redirect to log files, sadly.

Vega Strike boost log console output screenshot 2020-05-11

**Comment by stephengtuggy** [comment]
> Please merge master

Will do. It may take a little time though; there are several conflicting files now.

**Comment by Loki1950** [comment]
@stephengtuggy `./vegastrike > output.log 2>error.log
`

**Comment by stephengtuggy** [comment]
So I can add to the list of tests run, that I have now tested jumping as well.

When redirecting output to output.log and error.log, using a command such as the following:

```bash
./vegastrike --debug=2 >output.log 2>error.log
```

all the Boost::Log output goes to output.log.

**Comment by stephengtuggy** [comment]
Sweet! Thanks for the merge, @nabaco

**Comment by nabaco** [comment]
I think we should add a separate issue regarding the redirection of the logs into a standard file.

**Comment by stephengtuggy** [comment]
[error.log](https://github.com/vegastrike/Vega-Strike-Engine-Source/files/4611344/error.log)
[output.log](https://github.com/vegastrike/Vega-Strike-Engine-Source/files/4611345/output.log)

**Comment by stephengtuggy** [comment]
> I think we should add a separate issue regarding the redirection of the logs into a standard file.

Can you do that, @nabaco ?

Let me see if I understand correctly. Do we want the console output and error output **always** to go to a certain file location, instead of to the terminal? If so, would that be part of #95 ?

**Comment by BenjamenMeyer** [comment]
@stephengtuggy yes, it should only go to a file location, and yes that would be part of #95.

**Comment by Loki1950** [comment]
Expatiation of the earlier comment currently we create .vegastrike directly under Home but current practice is to put that folder in .config also the **save sectors serialized_xml sounds textures** should be under .local/share/.vegastrike extra work for us I know but it does seem to current practice to keep hidden files in those classifications

**Comment by nabaco** [comment]
Agreedm it's according the XDG specification. This is part of #97.

**Comment by ermo** [comment]
Guys, fatal errors really ought to be printed (or at least also copied) to stderr?

**Comment by nabaco** [comment]
> 
> 
> > > Let me see if I understand correctly. Do we want the console output and error output **always** to go to a certain file location, instead of to the terminal? If so, would that be part of #95 ?
> > 
> > 
> > yes, it should only go to a file location, and yes that would be part of #95.
> 
> Guys, fatal errors **_really_** ought to be printed (or at least also copied) to stderr?
> 
> Not doing so tends to break the principle of least astonishment.
> 
> Bonus points for posting a short text blurb after VS has exited with an error code, where the blurb points to the latest log file.

Agreed. Let's do this under a separate issue.

**Comment by BenjamenMeyer** [comment]
> > > Let me see if I understand correctly. Do we want the console output and error output **always** to go to a certain file location, instead of to the terminal? If so, would that be part of #95 ?
> > 
> > 
> > yes, it should only go to a file location, and yes that would be part of #95.
> 
> Guys, fatal errors **_really_** ought to be printed (or at least also copied) to stderr?
> 
> Not doing so tends to break the principle of least astonishment.

I would agree that would be in the exception to the rule portion. Let's update #95 for that.

**Pull request merged**
