### PR TITLE
Fix "no jump drive present" issue

### LINKED ISSUE #636: Game incorrectly says "No Drive" after buying and outfitting Determinant
During play testing, I bought a Determinant and upgraded it with a Jump Drive, among other things. Yet the game refuses to recognize that I have a jump drive. It shows up in the parts list, but when I look at the Info tab, it says, "No outsystem jump drive present." And when I launch into space, and try to fly through a jump point, it just says, "No Drive."

This is definitely a problem. I need to figure out what's going on before I merge this PR.

_Originally posted by @stephengtuggy in https://github.com/vegastrike/Vega-Strike-Engine-Source/issues/633#issuecomment-1003761934_

### PR DESCRIPTION
**Pull request by stephengtuggy**
Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [X] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [ ] This is a documentation change only

Issues:
- Please list any related issues
- Closes #636 

Purpose:
- What is this pull request trying to do? Fix the issue where the game does not recognize when you have a jump drive after purchasing a new ship
- What release is this for? 0.9.x
- Is there a project or milestone we should apply this to? 0.9.x

### CODE REVIEW

**Comment by stephengtuggy** [comment]
This fixes the issue for me. I did see the game segfault once when I launched into space after buying and outfitting a new ship. Haven't been able to reproduce that yet though. Hopefully it was a one-time occurrence.

But more testing is definitely needed.

**Comment by evertvorster** [comment]
Hey there!
Yeah, the Jump drives that I now buy are actually fitted to my ship, which is nice. 
But, I am running into another bug that I am not sure is related, though. 

When I first buy a Franklin milspec, it shows Warp capacitance to be 280 MJ, and capacitance needed to be about 200 MJ, so we're all good. When I save the game and restore it, the Warp capacitance now reads 40 MJ, which is not good enough anymore. Do you think it's related?

**Comment by evertvorster** [comment]
Sorry, some numbers got mangled here. 
When I first buy the Franklin, it's Warp capacitor capacity is 280 000 MJ, and the jump drive needs 250 000 MJ. After a save and restore, the ship's warp capacity is reduced to 40 000 MJ. It's either not saving the value correctly, or not reading it correctly...

**Comment by evertvorster** [comment]
Hmm, I bought yet another Franklin... I used the money cheat, and gave myself the maximum number of money to enable me to buy all these nice toys... So, before buying the last Franklin, I lobbed a digit off my money, and now the warp capacitor size issue seems gone. In any case, the initial bug about not fitting the jump drive is defenitely fixed with this PR

**Review by evertvorster — APPROVED** [review]

**Comment by stephengtuggy** [comment]
@evertvorster I think the latest issue you're seeing, with warp capacitor size, might be the same one originally filed as https://github.com/vegastrike/Vega-Strike-Engine-Source/issues/13 . Anyway, good to know that the issue at hand is fixed. Thanks for approving.

**Pull request merged**
