### PR TITLE
Adds an install target for the binaries.

### PR DESCRIPTION
**Pull request by evertvorster**
Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [ ] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [X] This is a documentation change only

Issues:
- Please list any related issues
cmake && make && make install is the canonical way of getting source installed on a system. Up to this PR, "make install" fails, claiming there is no target

Purpose:
- What is this pull request trying to do?
It helps anyone building from source, especially package maintainers.
If you are not doing a "make install", this change does not affect you. (Clearly this does not happen often, as the install target did not exist)

- What release is this for?
master
- Is there a project or milestone we should apply this to?
No.

### CODE REVIEW

**Comment by nabaco** [comment]
@BenjamenMeyer I'd say we need to cherry pick this to 0.6.x as it is relevant to the release.

@evertvorster - the changes seems to break compilation.

**Comment by evertvorster** [comment]
I am investigating now. Building worked on my machine, but of course it needs to work everywhere. I'll fix it and come back to you guys.

**Comment by evertvorster** [comment]
@nabaco, found the error, and an apparent way to fix it without having to play around with sources on my machine.

**Comment by BenjamenMeyer** [comment]
@nabaco 0.6.x might already have it or something close. Please verify.

**Pull request merged**
