### PR TITLE
Big refactor to fix crash in mesh destructor

### LINKED ISSUE #716: Unit destructor crashes the game
Sometimes, when a unit is destroyed, the game crashes.

Stack Trace:
`#13 0x000055a645097aaa in std::vector<Mesh*, std::allocator<Mesh*> >::_M_range_check (
    __n=18446744073709551615, this=0x55a653939740)
    at /usr/include/c++/11/bits/hashtable_policy.h:387
#14 std::vector<Mesh*, std::allocator<Mesh*> >::at (__n=18446744073709551615, 
    this=0x55a653939740) at /usr/include/c++/11/bits/stl_vector.h:1094
#15 Mesh::~Mesh (this=0x55a65393a498, __in_chrg=<optimized out>)
    at /home/roy/git/vegastrike/Vega-Strike-Engine-Source/engine/src/gfx/mesh_gfx.cpp:442
#16 0x000055a645097ce2 in Mesh::~Mesh (this=0x55a6539a6c50, __in_chrg=<optimized out>)
    at /home/roy/git/vegastrike/Vega-Strike-Engine-Source/engine/src/gfx/mesh_gfx.cpp:461
#17 0x000055a645097d5f in Mesh::~Mesh (this=0x55a6539a6c50, __in_chrg=<optimized out>)
    at /home/roy/git/vegastrike/Vega-Strike-Engine-Source/engine/src/gfx/mesh_gfx.cpp:407
#18 0x000055a64544481a in Unit::~Unit (this=0x55a653938670, __in_chrg=<optimized out>)
    at /usr/include/c++/11/bits/stl_vector.h:1043
#19 0x000055a645444c5f in Unit::~Unit (this=0x55a653938670, __in_chrg=<optimized out>)
    at /home/roy/git/vegastrike/Vega-Strike-Engine-Source/engine/src/cmd/unit_generic.cpp:326`

### PR DESCRIPTION
**Pull request by stephengtuggy**
Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [Partially] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation

Issues:
- Fixes #716 

Purpose:
- What is this pull request trying to do? Refactor `Mesh`; `AnimatedTexture`; and related classes, to use smart pointers (among other things), for improved memory safety and fewer crashes
- What release is this for? 0.9.x, preferably
- Is there a project or milestone we should apply this to? 0.9.x

### CODE REVIEW

**Review by BenjamenMeyer — APPROVED** [review]

**Comment by stephengtuggy** [comment]
Known issue: main menu, various other pre-rendered screens not rendering, except for a solid background color. (They are still clickable, however.) (Yeah, this one's kind of a big deal.)

**Comment by stephengtuggy** [comment]
Known issue: Various drawn objects flickering, like the occlusion calculations aren't working correctly, causing the inside or back side of an object to show through.

**Comment by stephengtuggy** [comment]
Known issue: When bolts are fired, game crashes while trying to process them / update their physics. (Fix in progress.)

**Comment by stephengtuggy** [comment]
Known issue: Armor and shield indicators not rendering on VDUs.

**Pull request merged**
