### PR TITLE
Maintenance: Updated Supported Linux Distros

### PR DESCRIPTION
**Pull request by BenjamenMeyer**
Code Changes:
- [ ] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [ ] This is a documentation change only
- [x] CI change

### CODE REVIEW

**Review by royfalk — APPROVED** [review]
I admit I did not review this thoroughly. It looks fine though.
If it were up to me, I'd simplify this somewhat by dropping support even in error message. i.e. only have 'this version of * linux is not supported'.

**Comment by BenjamenMeyer** [comment]
Trying to figure out what's wrong with the Rocky Linux 8.10 before merging

**Comment by BenjamenMeyer** [comment]
Dropping Rocky Linux 8.10 for the time being

**Comment by BenjamenMeyer** [comment]
> I'd simplify this somewhat by dropping support even in error message. i.e. only have 'this version of * linux is not supported'.

That'd probably a good follow-up PR for to this. Do agree with need to clean things up a bit.

**Comment by BenjamenMeyer** [comment]
Merging based on https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/890#pullrequestreview-2360289474 and conversation in gitter.im.

**Pull request merged**
