### PR TITLE
Fix save game bug

### LINKED ISSUE #747: Savegames, when loaded, are missing the player's ship
When I load a savegame that was generated using a recent build of Vega Strike, my ship is gone.

Savegames generated using previous builds do not have this problem.

### PR DESCRIPTION
**Pull request by royfalk**
closes #747 

Code Changes:
- [x] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
    _I've also ran some basic tests and ran extensive tests on the specific problem in question._

Issues:
- Overwriting save game, leaves the old ship file in the ship folder if it is not the same. #755

### CODE REVIEW

**Comment by royfalk** [comment]
What's up with the windows CI fails? I doubt this is related to my PR.

**Comment by stephengtuggy** [comment]
> What's up with the windows CI fails? I doubt this is related to my PR.

The Windows CI builds are failing on [line 38 of csv.h](https://github.com/vegastrike/Vega-Strike-Engine-Source/blob/task_fix_736/engine/src/cmd/csv.h#L38) , while building `vegastrike-testing`. The error is `error C2039: 'map': is not a member of 'std'`.

TBH, I'm surprised that this file is compiling at all, on any platform. It ought to `#include <map>`, but it doesn't. I'm not finding any transitive includes of the `map` header file, either -- just `<unordered_map>`, in gnuhash.h.

I think adding the `#include <map>` line to csv.h will probably fix the errors.

**Comment by stephengtuggy** [comment]
Other than that, it's looking good, as far as I can see. I would like to see one of us run through the standard set of PR Validation Tests though, before we merge this.

**Comment by royfalk** [comment]
> Other than that, it's looking good, as far as I can see. I would like to see one of us run through the standard set of PR Validation Tests though, before we merge this.

Ran the full tests successfully. If the windows CI passes, I think we're good to merge.

**Review by stephengtuggy — APPROVED** [review]

**Pull request merged**
