### PR TITLE
Add base name and type to base computer header

### PR DESCRIPTION
**Pull request by ermo**
In Priv:WCU, it is very convenient to be able to check the name and type
of the current base when trading via the base computer, since the
computer tracks the prices seen at other in-system bases.

### CODE REVIEW

**Comment by stephengtuggy** [comment]
Hmm. Why the force-push, @ermo ? I am generally wary when I see one of those.

**Comment by ermo** [comment]
> Hmm. Why the force-push, @ermo ? I am generally wary when I see one of those.

Typo in commit message header ('type' instead of 'typo'). That's the only difference.  I figured that since it's a short-lived branch, force-pushing would be ok.

**Comment by ermo** [comment]
> Looks good to me. Can you supple a couple of screen shots how it actually looks in the game?

https://imgur.com/a/mS2RLqC (don't know how long the imgur link will work, but there you go)

**Comment by nabaco** [comment]
Have you tested it with the UtCS data-set?

**Comment by ermo** [comment]
> Have you tested it with the UtCS data-set?

The top image is from the UtCS data-set, so yes -- but only a cursory test where I load up the game and verify that it looks nice enough on the starting planet.

**Pull request merged**
