### PR TITLE
Homebrew Troubleshooting - 0.8.x

### LINKED ISSUE #812: Some macOS builds failing due to Python version conflicts
(Python 3.11 vs. Python 3.12.) Boost Python is apparently trying to use the wrong one, or something.

### PR DESCRIPTION
**Pull request by stephengtuggy**
Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [ ] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation

Issues:
Further fixes #812  

Purpose:
- What is this pull request trying to do? Make macOS CI builds more reproducible, so that they pass more consistently
- What release is this for? 0.8.x
- Is there a project or milestone we should apply this to? 0.8.x

### CODE REVIEW

**Comment by stephengtuggy** [comment]
Hey, guys. With this PR, 0.8.x should both build consistently and run on macOS. Can I get some reviews, please? And some testing is also needed, esp. on Mac. I will see if I can do some of that.

**Review by BenjamenMeyer — APPROVED** [review]
LGTM - is there anything we need to port to 0.9.x and master?

**Comment by stephengtuggy** [comment]
> LGTM - is there anything we need to port to 0.9.x and master?

Yes, we will probably need to port quite a few of these changes to 0.9.x and to master. Those items will need to be on the project board(s), huh?

**Comment by stephengtuggy** [comment]
So this PR has been merged, judging from the contents of the 0.8.x branch. But the PR screen doesn't show it. Weird.

I think I will just close this Pull Request, noting that it has, in fact, been merged.

**Comment by stephengtuggy** [comment]
Hmm. Maybe this PR didn't get merged after all. Reopening.

**Comment by stephengtuggy** [comment]
The Rocky Linux 8.7 failure is expected; the code no longer builds on Rocky Linux 8.x, and as such, I guess we are no longer supporting it.

**Comment by stephengtuggy** [comment]
Good. Now it's merged.

**Pull request merged**
