### PR TITLE
Task more config

### PR DESCRIPTION
**Pull request by royfalk**
Primarily, this now allows the player to set certain factors for fuel, reactor, etc.
This is complemented by an  [Assets PR](https://github.com/vegastrike/Assets-Production/pull/137).

Code Changes:
- [X] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation minimal. Game works and setting fuel to 0.1 makes it run out very quickly.

### CODE REVIEW

**Comment by royfalk** [comment]
Can I get a review of the branch?

**Comment by royfalk** [comment]
> When starting a new game, and then going straight into Ship Info, I can see the turning response is 0.

I assume this is #924 . Given we have a fix in the works, let's ignore it here.

**Review by BenjamenMeyer — APPROVED** [review]

**Review by evertvorster — APPROVED** [review]
The issues I have seen in this branch are indeed gone, and now everything looks perfect.

**Comment by royfalk** [comment]
Fixed the issue you mentioned in https://github.com/vegastrike/Assets-Production/pull/137.
However, note that actual figure reported by fuel does not make sense. We'll need to adjust this number further for all ships. 

We'll also need to document everything and possibly create a guide of some kind.

**Pull request merged**
