### PR TITLE
Enhancement: Added notes for contributors regarding packaging

### PR DESCRIPTION
**Pull request by BenjamenMeyer**
Notes for packaging contributors

Code Changes:
- [ ] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [x] This is a documentation change only

Issues:
- #131 
- #135

### CODE REVIEW

**Comment by BenjamenMeyer** [comment]
@evertvorster would appreciate any feedback you have on this as well since folks like you are the primary audience.

**Comment by evertvorster** [comment]
Hi Benjamin. My requirements for packaging are quite simple. 
Once you are happy to release, make & host a tarballs of the source + data. (and tell me about it)
I'll make the packages for Arch AUR that uses those released tarballs.

If you do want to make my life a little easier, consider adding an install target for make or cmake. 

One little wrinkle that is a little confusing to me. 

The data files end up in /usr/share/vegastrike
The binary files end up in /usr/bin

When I run vegasettings from my home directory, it complains about not finding Version.txt.
Since this file ended up in /usr/share/vegstrike, when I run it from there, vegasettings works fine.
What is the proper location for Version.txt so that vegasettings can find it?

**Comment by BenjamenMeyer** [comment]
@evertvorster yeah, that's something we need to fix. Probably will be in 0.7.x.

Just set the working directory for now.

**Comment by stephengtuggy** [comment]
One thing you might try is create a symbolic link to the data files directory (which is the proper location for Version.txt). The symbolic link can be named `data`, `Resources`, or `Assets-Production`. I.e.:

```bash
cd /usr/bin
ln -s /usr/share/vegastrike Assets-Production
```

The relevant section of code is in engine/src/vsfilesystem.cpp. Function `void InitDataDirectory()`

**Pull request merged**
